name: Deploy to Docker Hub and EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vite-react-app:latest
          build-args: |
            VITE_APP_SERVER_HOST=${{ secrets.VITE_APP_SERVER_HOST }}

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/vite-react-app:latest

            # Run the new container
            docker run -d -p 3000:3000 --name vite-react-app-new -e VITE_APP_SERVER_HOST=${{ secrets.VITE_APP_SERVER_HOST }} ${{ secrets.DOCKER_USERNAME }}/vite-react-app:latest

            # Wait for the new container to be healthy (adjust the sleep time as needed)
            sleep 10

            # Remove the old container
            docker stop vite-react-app || true
            docker rm vite-react-app || true

            # Rename the new container to the old container's name
            docker rename vite-react-app-new vite-react-app
          EOF
